apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hdcrs-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - kind.neo.nsstc.uah.edu
    secretName: ingress-tls
  rules:
  - host: kind.neo.nsstc.uah.edu
    http:
      paths:
      - path: /hdcrs/api
        pathType: Prefix
        backend:
          service:
            name: hdcrs-service
            port:
              number: 443

