apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdcrs-cache-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/hdcrs-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdcrs-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---

